app = "bx-platform"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[deploy]
  strategy = "immediate"
